[package]
name = "kanjitomo-rs"
description = "Rewrite of Kanjitomo OCR in rust"
version = "0.1.0"
authors = ["Kirill Mironov @ vetrokm@gmail.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.4"